### ISSUE TITLE
Customized schema is defined and commit. but still use SPG_KGPrompt for KAGExtractor

### ISSUE THREAD

**Issue by pecanjk** [OpenSPG/KAG#103]
After I define my own Customized schema as Cust.schema and commit successfully. but from the ollama server end I can findout it still use a SPG_KGPrompt for KAGExtractor. I'm not sure if it has bad effect or not since the customized schema is quite different from the SPG_KGPrompt. And how to use my own schema definition and examples? Thanks.

This are the ollama server terminal output
> time=2024-12-06T11:11:29.681+08:00 level=DEBUG source=routes.go:270 msg="generate request" images=0 prompt="<|start_header_id|>system<|end_header_id|>\n\nCutting Knowledge Date: December 2023\n\n<|eot_id|><|start_header_id|>user<|end_header_id|>\n\n\n    {\n        \"instruction\": \"你是一个图谱知识抽取的专家, 基于constraint 定义的schema，从input 中抽取出所有的实体及其属性，input中未明确提及的属性返回NAN，以标准json 格式输出，结果返回list\",\n        \"schema\": {'Zone': {'properties': {'hasBuilding': '包含建筑', 'operationType': '运维方式', 'compliance': '应符合规范', 'attribute': '关联属性'}}, 'System': {'properties': {'compliance': '应符合规范', 'operationType': '运维方式', 'attribute': '关联属性', 'hasDevice': '包含设备'}}, 'Building': {'properties': {'compliance': '应符合规范', 'hasSystem': '包含系统', 'attribute': '关联属性', 'operationType': '运维方式'}}, 'Attribute': {'properties': {'operationType': '运维方式'}}, 'Standard': {'properties': {'equation': '关联指标公式', 'itemNumber': '条目编号', 'criteriaValue': '评价分值', 'criteria': '比较词', 'itemContent': '条目内容'}}},\n        \"example\": [\n        {\n            \"input\": \"甲状腺结节是指在甲状腺内的肿块，可随吞咽动作随甲状腺而上下移动，是临床常见的病症，可由多种病因引起。临床上有多种甲状腺疾病，如甲状腺退行性变、炎症、自身免疫以及新生物等都可以表现为结节。甲状腺结节可以单发，也可以多发，多发结节比单发结节的发病率高，但单发结节甲状腺癌的发生率较高。患者通常可以选择在普外科，甲状腺外科，内分泌科，头颈外科挂号就诊。有些患者可以触摸到自己颈部前方的结节。在大多情况下，甲状腺结节没有任何症状，甲状腺功能也是正常的。甲状腺结节进展为其它甲状腺疾病的概率只有1%。有些人会感觉到颈部疼痛、咽喉部异物感，或者存在压迫感。当甲状腺结节发生囊内自发性出血时，疼痛感会更加强烈。治疗方面，一般情况下可以用放射性碘治疗，复方碘口服液(Lugol液)等，或者服用抗甲状腺药物来抑制甲状腺激素的分泌。目前常用的抗甲状腺药物是硫脲类化合物，包括硫氧嘧啶类的丙基硫氧嘧啶(PTU)和甲基硫氧嘧啶(MTU)及咪唑类的甲硫咪唑和卡比马唑。\",\n            \"schema\": {\n                \"Disease\": {\n                    \"properties\": {\n                        \"complication\": \"并发症\",\n                        \"commonSymptom\": \"常见症状\",\n                        \"applicableMedicine\": \"适用药品\",\n                        \"department\": \"就诊科室\",\n                        \"diseaseSite\": \"发病部位\",\n                    }\n                },\"Medicine\": {\n                    \"properties\": {\n                    }\n                }\n            }\n            \"output\": [\n                {\n                    \"entity\": \"甲状腺结节\",\n                    \"category\":\"Disease\"\n                    \"properties\": {\n                        \"complication\": \"甲状腺癌\",\n                        \"commonSymptom\": [\"颈部疼痛\", \"咽喉部异物感\", \"压迫感\"],\n                        \"applicableMedicine\": [\"复方碘口服液(Lugol液)\", \"丙基硫氧嘧啶(PTU)\", \"甲基硫氧嘧啶(MTU)\", \"甲硫咪唑\", \"卡比马唑\"],\n                        \"department\": [\"普外科\", \"甲状腺外科\", \"内分泌科\", \"头颈外科\"],\n                        \"diseaseSite\": \"甲状腺\",\n                    }\n                },{\n                    \"entity\":\"复方碘口服液(Lugol液)\",\n                    \"category\":\"Medicine\"\n                },{\n                    \"entity\":\"丙基硫氧嘧啶(PTU)\",\n                    \"category\":\"Medicine\"\n                },{\n                    \"entity\":\"甲基硫氧嘧啶(MTU)\",\n                    \"category\":\"Medicine\"\n                },{\n                    \"entity\":\"甲硫咪唑\",\n                    \"category\":\"Medicine\"\n                },{\n                    \"entity\":\"卡比马唑\",\n                    \"category\":\"Medicine\"\n                }\n            ],\n    \"input\": \"KagDemo3_all_text\n3倍；\n    2 流量传感器安装位置前后应有保证产品所要求的直管段长度或其他安装条件；\n    3 应选用具有瞬态值输出的流量传感器；\n    4 

The ner/std/triple.py inside prompt folder can work as expected.

**Comment by pecanjk** [comment]
I thought it maybe better to use my own schema definition as constraint and also provide customized examples? similar as builder/prompt/ner.py

**Comment by thundax-lyp** [comment]
需要调整你的schema

在 KAGExtractor(https://github.com/OpenSPG/KAG/blob/master/kag/builder/component/extractor/kag_extractor.py) (LN59)中，会检测 self.schema 中的定义，当类型不在 SPG_KGPrompt.ignored_types 且属性不在SPG_KGPrompt.ignored_properties里的时候，会使用 SPG_KGPrompt

**Comment by pecanjk** [comment]
在 [KAGExtractor](https://github.com/OpenSPG/KAG/blob/master/kag/builder/component/extractor/kag_extractor.py) (LN95)中是将kg_result和ner_result拼接在一起的，我理解是为了补充未定义的部分内容，实际上我希望kg_result得到的结果，尤其是属性内容，用我自己的prompt，但是没法像build/prompt/ner.py那样引入

**Comment by thundax-lyp** [comment]
> 在 [KAGExtractor](https://github.com/OpenSPG/KAG/blob/master/kag/builder/component/extractor/kag_extractor.py) (LN95)中是将kg_result和ner_result拼接在一起的，我理解是为了补充未定义的部分内容，实际上我希望kg_result得到的结果，尤其是属性内容，用我自己的prompt，但是没法像build/prompt/ner.py那样引入

LN59,这段
![screenshot](https://github.com/user-attachments/assets/9826dd1b-40d6-4732-9731-a2adec37f3af)

**Comment by thundax-lyp** [comment]
> 在 [KAGExtractor](https://github.com/OpenSPG/KAG/blob/master/kag/builder/component/extractor/kag_extractor.py) (LN95)中是将kg_result和ner_result拼接在一起的，我理解是为了补充未定义的部分内容，实际上我希望kg_result得到的结果，尤其是属性内容，用我自己的prompt，但是没法像build/prompt/ner.py那样引入

可以构建自己的BuilderChain。
例子里的顺序是 reader >> splitter >> extractor >> vectorizer >> writer，可以重写Extractor，能够输出List[SubGraph]给后续节点就可以了
