### ISSUE TITLE
你好针对HotpotQA、2WikiMultiHopQA、MuSiQue评测的结果，数据源有吗？

### ISSUE THREAD

**Issue by zchengzhong** [OpenSPG/KAG#15]
你好针对HotpotQA、2WikiMultiHopQA、MuSiQue评测的结果，数据源有吗？
如果没有源，假设直接用现成的那些数据集中的问答对，当作数据源，那测试结论应该没有较大的参考性。
请问是有独立的源吗？

**Comment by caszkgui** [comment]
> 你好针对HotpotQA、2WikiMultiHopQA、MuSiQue评测的结果，数据源有吗？ 如果没有源，假设直接用现成的那些数据集中的问答对，当作数据源，那测试结论应该没有较大的参考性。 请问是有独立的源吗？

Dataset for HotpotQA、2WikiMultiHopQA、MuSiQue have been uploaded to kag/examples/xx/builder/data directory.
