### ISSUE TITLE
本地运行时经常出现写入neo4j失败，有时还会出现代码运行卡死的情况

### ISSUE THREAD

**Issue by JaDonghao** [OpenSPG/KAG#151]
### Search before asking

- [X] I had searched in the [issues](https://github.com/OpenSPG/KAG/issues?q=is%3Aissue) and found no similar issues.

### Operating system information

Linux

### What happened

本地运行时经常出现写入neo4j失败，有时还会出现代码运行卡死的情况，重启三个服务mysql、neo4j、server之后就可以了。请问这是有什么限制吗，使用csv格式时，文档数量以及每篇文档token有限制吗？运行kag有什么配置要求吗

### How to reproduce

使用csv格式时，每篇文章token数在20000以上时出现写入neo4j失败，且之后所有写入都失败；不知道什么原因经常出现代码运行卡死的情况。

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by thundax-lyp** [comment]
could you like to provide more detailed information? such as kag_config.cfg, indexer.py and your CSV corpus.

**Comment by thundax-lyp** [comment]
> ### Search before asking
> * [x]  I had searched in the [issues](https://github.com/OpenSPG/KAG/issues?q=is%3Aissue) and found no similar issues.
> 
> ### Operating system information
> Linux
> 
> ### What happened
> 本地运行时经常出现写入neo4j失败，有时还会出现代码运行卡死的情况，重启三个服务mysql、neo4j、server之后就可以了。请问这是有什么限制吗，使用csv格式时，文档数量以及每篇文档token有限制吗？运行kag有什么配置要求吗
> 
> ### How to reproduce
> 使用csv格式时，每篇文章token数在20000以上时出现写入neo4j失败，且之后所有写入都失败；不知道什么原因经常出现代码运行卡死的情况。
> 
> ### Are you willing to submit PR?
> * [ ]  Yes I am willing to submit a PR!

从代码上看，openspg-server上周修复了这个问题，等待新的docker包吧，或者下载最新的openspg-server代码。

**Comment by andylau-55** [comment]
Thanks for the feedback. Please pull the latest opengspg-server image
