### ISSUE TITLE
[Doc][Module Name] Are there any models other than deepseek-chat supported?

### ISSUE THREAD

**Issue by mctouch** [OpenSPG/KAG#175]
### Search before asking

- [X] I had searched in the [issues](https://github.com/OpenSPG/KAG/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Are there any models other than deepseek-chat supported where I don't have to get a credit card out?

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by vcpandya** [comment]
Yes just use config as
{"api_key":"your-api-key","base_url":"https://api.openai.com/v1","model":"gpt-4o","client_type":"maas"}
