### ISSUE TITLE
原始TXT中有个“尚文婷”，但抽取结果中除了尚文婷，还有个尚雯婷

### ISSUE THREAD

**Issue by jt6371** [OpenSPG/KAG#21]
可能和上一个ISSUES（中文变英文）是类似的问题，在抽取过程中进行了中英文转化。
测试TXT见附件
[温人大〔2023〕4号.txt](https://github.com/user-attachments/files/17614480/2023.4.txt)
![微信图片_20241104133046](https://github.com/user-attachments/assets/0425e6ca-aaa5-4a4e-b5dd-06dd275e753c)

**Comment by caszkgui** [comment]
> 可能和上一个ISSUES（中文变英文）是类似的问题，在抽取过程中进行了中英文转化。 测试TXT见附件 [温人大〔2023〕4号.txt](https://github.com/user-attachments/files/17614480/2023.4.txt) ![微信图片_20241104133046](https://private-user-images.githubusercontent.com/187242096/382661621-0425e6ca-aaa5-4a4e-b5dd-06dd275e753c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3MDMyOTAsIm5iZiI6MTczMDcwMjk5MCwicGF0aCI6Ii8xODcyNDIwOTYvMzgyNjYxNjIxLTA0MjVlNmNhLWFhYTUtNGE0ZS1iNWRkLTA2ZGQyNzVlNzUzYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNFQwNjQ5NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yN2E3ODBmN2JlY2JmNjQ3NjFiZDRkNDhmM2Q4NDdhMjhhYjJlODhmZGI2YTVmZGE3OGE4NmQ4OWVkNzBjMGU3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Xmr6ibtsMSRwPg0fR4mjc1T89jHOrpZ1sDheUmcM0mk)

could you paste your llm conf here ?

**Comment by jt6371** [comment]
> could you paste your llm conf here ?
thank you:
{"base_url":"http://192.168.0.104:11434","model":"qwen2.5:3b","client_type":"ollama"}

**Comment by mars216** [comment]
你好，请问这个数据库界面怎么打开的呀

**Comment by caszkgui** [comment]
> 你好，请问这个数据库界面怎么打开的呀

default host of neo4j web ui is: http://127.0.0.1:7474/browser/

**Comment by mars216** [comment]
docker中neo4j的默认用户名和密码是多少呀

**Comment by caszkgui** [comment]
> docker中neo4j的默认用户名和密码是多少呀

user name and password of neo4j container can be found in [docker-compose](https://github.com/OpenSPG/openspg/blob/master/dev/release/docker-compose.yml)
