### ISSUE TITLE
ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by PimelY567** [OpenSPG/KAG#23]
buildKB successfully for /teamspace/studios/this_studio/KAG/kag/examples/hotpotqa/builder/./data/hotpotqa_sub_corpus.json

parallelQaAndEvaluate completing:   0%|                   | 0/2 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/teamspace/studios/this_studio/KAG/kag/examples/hotpotqa/./solver/evaForHotpotqa.py", line 46, in process_sample
    prediction, traceLog = self.qa(question)
  File "/teamspace/studios/this_studio/KAG/kag/examples/hotpotqa/./solver/evaForHotpotqa.py", line 25, in qa
    resp = SolverPipeline()
  File "/teamspace/studios/this_studio/KAG/kag/solver/logic/solver_pipeline.py", line 26, in __init__
    self.memory = DefaultMemory(**kwargs)
  File "/teamspace/studios/this_studio/KAG/kag/solver/implementation/default_memory.py", line 9, in __init__
    super().__init__(**kwargs)
  File "/teamspace/studios/this_studio/KAG/kag/interface/solver/kag_memory_abc.py", line 13, in __init__
    super().__init__(**kwargs)
  File "/teamspace/studios/this_studio/KAG/kag/solver/common/base.py", line 114, in __init__
    self.language = self.config.get("prompt").get("language") or os.getenv("KAG_PROMPT_LANGUAGE", "en")
AttributeError: 'NoneType' object has no attribute 'get'
WARNING:__main__:process sample failed with error:None
for: (0, {'supporting_facts': [['Alû', 3], ['Lilu (mythology)', 0]], 'level': 'easy', 'question': 'If Gallu is a demon Lilu is what?', 'context': [['Demon Dice', ['Demon Dice, originally published as Chaos Progenitus, is a collectible dice game created by Lester Smith (designer of the better-known Dragon Dice) and Tim Brown.', " In it, each player controls a demon made of 13 dice representing body parts (or magical items wielded by those parts), which battles the other player's demon.", ' The original Chaos Progenitus version presented the concept of these dueling fiends seriously; when the game was republished as Demon Dice by Fast Forward Games (which has since gone out of business), the idea was given a humorous spin, styling the players as "Demon Creation Specialists, Junior Grade" in the bureaucracy of Hell.', ' Neither version of the game was a great commercial success, though they retain a small and loyal fanbase.']], ['Demon algorithm', ['The demon algorithm is a Monte Carlo method for efficiently sampling members of a microcanonical ensemble with a given energy.', " An additional degree of freedom, called 'the demon', is added to the system and is able to store and provide energy.", ' If a drawn microscopic state has lower energy than the original state, the excess energy is transferred to the demon.', ' For a sampled state that has higher energy than desired, the demon provides the missing energy if it is available.', ' The demon can not have negative energy and it does not interact with the particles beyond exchanging energy.', ' Note that the additional degree of freedom of the demon does not alter a system with many particles significantly on a macroscopic level.']], ['Maha Sona', ['Maha Sona or Maha Sohona (Sinhala: මහ සෝනා, මහ සොහොනා) is a "yaka" (or "yakseya" or "devaya", meaning demon) in Sinhalese folklore, who is said to haunt afterlife.', ' The name Maha Sona means " the greatest demon" or "god or demon of the cemetery" in the Sinhala language.', ' It is the most feared god or demon in Sri Lanka.', ' Originally a giant who had been defeated and decapitated in a duel by another giant named Gotaimbara (lived in the 1st century BC), Maha Sonaa has had his head replaced with that of a bear or tiger.', ' He is believed to kill people by crushing their shoulders and also by afflicting illnesses.', ' Traditional exorcism rituals are performed to repel the demon in such cases.', ' Sri Lanka Army\'s Long Range Reconnaissance Patrol units are popularly known as the "Maha Sohon Brigade", named after this demon.']], ['Wangliang', ['Wangliang (魍魎 or 罔两) is the name of a malevolent spirit in Chinese mythology and folklore.', ' This word inclusively means "demons; monsters; specters; goblins; ghosts; devils" in Modern Standard Chinese, but "wangliang" originally meant a specific demon.', ' Interpretations include a wilderness spirit like the "kui" 夔 "one-legged mountain demon", a water spirit like the "long" 龍 "dragon", a fever demon like the "yu" 魊 "poisonous 3-legged turtle that causes malaria", a graveyard ghost also called wangxiang 罔象 or fangliang 方良 "earth demon that eats the livers or brains of corpses", and a man-eating "demon that resembles a 3-year-old brown child with red eyes, long ears, and beautiful hair".']], ['The Hythrun Chronicles', ['The Hythrun Chronicles is a fantasy set of novels by Jennifer Fallon told in two trilogies, The Demon Child Trilogy and The Wolfblade Trilogy.', " The Demon Child Trilogy follows R'shiel Tenragan as she accepts her fate as the demon child and tries to hold the fabric of her world together while defeating the Karien god, Xaphista, and bringing about some well needed changes to the four main countries of Medalon, Hythria, Fardohnya, and Karien with help from multiple influential characters she befriends.", " The Wolfblade Trilogy, set about 30 years before, follows the life of Marla Wolfblade from the age of 15 until she is in her 40's.", " It also follows stories of various characters intertwined with that of Marla Wolfblade and explains much of the history in The Demon Child History as it follows Damin Wolfblade and Marla's other children growing up and how the state of affairs presented in The Demon Child Trilogy came to be.", ' There is a fifth country introduced to the trilogy as well, Denika.', ' It is off the map and indicated as south of Hythria and Fardohnya across the Dregian Ocean, accessed by ship.']], ['Lilu (mythology)', ['A lilu or lilû is a masculine Akkadian word for a spirit, related to Alû, demon.']], ['Leyenda de Azul', ['The Leyenda de Azul (Spanish for "the Blue Legend") is a lucha libre tournament held seven times by the Mexican professional wrestling promotion Consejo Mundial de Lucha Libre (CMLL) between 2000 and 2008 and again in 2011 and 2012.', ' The tournament honors Blue Demon, or "Demonio Azul" as he\'s sometimes referred to.', ' The tournament is not nearly as prestigious as CMLL\'s annual "Leyenda de Plata" tournament.', ' The winner is given a plaque with a Blue Demon mask on it and a championship belt featuring Blue Demon as well.', ' There was no "Leyenda de Azul" in 2009 and no plans for a 2010 tournament has been announced so far.', " All tournaments have taken place in Arena México in Mexico City and all were held on Fridays during CMLL's Super Viernes show.", " In 2009 Blue Demon Jr. threatened to take legal action against CMLL on behalf of the National Wrestling Alliance over CMLL's use of three NWA branded championships.", ' While CMLL did not publicly respond to the threat they dropped the tournament from their schedule for two years.', ' In July 2011, CMLL, still not on good terms with Blue Demon Jr., announced the return of the tournament.', " The tournament would instead be endorsed by Blue Demon's biological son and Blue Demon Jr.'s adopted brother, El Hijo de Blue Demon."]], ['Lilu (ancient China)', ['Lilu () was a legendary tribe or state of ancient China.', ' According to legends recorded in the third-century text "Records of Emperors and Kings" (帝王世纪) by Huangfu Mi, goddess Nüwa enfeoffed thirteen tribes or states, all having the Feng (风) surname.', ' Lilu was ranked the fourth among the thirteen.', ' Lilu is also mentioned in many other ancient texts including "Zhuangzi", and "Dengzi" by Deng Xi.', ' Professor Li Yujie of Henan University believes that Lilu was likely the first people in China to cultivate chestnuts (The "li" in Lilu means chestnut).', ' The Li (栗) surname is believed to have originated from the tribe.']], ['Arthur? Arthur!', ['Arthur?', ' Arthur!', ' is a 1969 British comedy film directed by Samuel Gallu and starring Shelley Winters, Donald Pleasence and Terry-Thomas.', ' The plot follows a dull and unsuccessful inventor who begins to develop a second identity as a man about town with a completely different life.']], ['Alû', ['In Akkadian and Sumerian mythology, Alû is a vengeful spirit of the Utukku that goes down to the underworld Kur.', ' The demon has no mouth, lips or ears.', ' It roams at night and terrifies people while they sleep, and possession by Alû results in unconsciousness and coma; in this manner it resembles creatures such as the mara, and incubus, which are invoked to explain sleep paralysis.', ' In Akkadian and Sumerian mythology, it is associated with other demons like Gallu and Lilu.']]], 'answer': 'a spirit', '_id': '5a77ec115542992a6e59dff7', 'type': 'bridge'})
Traceback (most recent call last):
  File "/teamspace/studios/this_studio/KAG/kag/examples/hotpotqa/./solver/evaForHotpotqa.py", line 46, in process_sample
    prediction, traceLog = self.qa(question)
  File "/teamspace/studios/this_studio/KAG/kag/examples/hotpotqa/./solver/evaForHotpotqa.py", line 25, in qa
    resp = SolverPipeline()
  File "/teamspace/studios/this_studio/KAG/kag/solver/logic/solver_pipeline.py", line 26, in __init__
    self.memory = DefaultMemory(**kwargs)
  File "/teamspace/studios/this_studio/KAG/kag/solver/implementation/default_memory.py", line 9, in __init__
    super().__init__(**kwargs)
  File "/teamspace/studios/this_studio/KAG/kag/interface/solver/kag_memory_abc.py", line 13, in __init__
    super().__init__(**kwargs)
  File "/teamspace/studios/this_studio/KAG/kag/solver/common/base.py", line 114, in __init__
    self.language = self.config.get("prompt").get("language") or os.getenv("KAG_PROMPT_LANGUAGE", "en")
AttributeError: 'NoneType' object has no attribute 'get'
WARNING:__main__:process sample failed with error:None
for: (1, {'supporting_facts': [['Christopher Nolan', 0], ['Sathish Kalathil', 0]], 'level': 'medium', 'question': 'Are Christopher Nolan and Sathish Kalathil both film directors?', 'context': [['Christopher Nolan', ['Christopher Edward Nolan ( ; born 30 July 1970) is an English-American film director, producer, and screenwriter.', ' He is one of the highest-grossing directors in history, and among the most successful and acclaimed filmmakers of the 21st century.']], ['The Prestige (film)', ["The Prestige is a 2006 British-American mystery thriller film directed by Christopher Nolan, from a screenplay adapted by Nolan and his brother Jonathan from Christopher Priest's 1995 novel of the same name.", ' Its story follows Robert Angier and Alfred Borden, rival stage magicians in London at the end of the 19th century.', ' Obsessed with creating the best stage illusion, they engage in competitive one-upmanship with tragic results.', ' The film stars Hugh Jackman as Robert Angier, Christian Bale as Alfred Borden, and David Bowie as Nikola Tesla.', ' It also stars Scarlett Johansson, Michael Caine, Piper Perabo, Andy Serkis, and Rebecca Hall.', ' The film reunites Nolan with actors Bale and Caine from "Batman Begins" and returning cinematographer Wally Pfister, production designer Nathan Crowley, film score composer David Julyan, and editor Lee Smith.']], ['The Dark Knight Rises', ['The Dark Knight Rises is a 2012 superhero film directed by Christopher Nolan, who co-wrote the screenplay with his brother Jonathan Nolan, and the story with David S. Goyer.', ' Featuring the DC Comics character Batman, the film is the final installment in Nolan\'s "Batman" film trilogy, and the sequel to "Batman Begins" (2005) and "The Dark Knight" (2008).', ' Christian Bale reprises the lead role of Bruce Wayne/Batman, with a returning cast of allies: Michael Caine as Alfred Pennyworth, Gary Oldman as James Gordon, and Morgan Freeman as Lucius Fox.', ' The film introduces Selina Kyle (Anne Hathaway), and Bane (Tom Hardy).', ' Eight years after the events of "The Dark Knight", merciless revolutionary Bane forces an older Bruce Wayne to resume his role as Batman and save Gotham City from nuclear destruction.']], ['Veena Vaadanam', ['Veena Vaadanam (Recital of Music) (മലയാളം: ) is an Indian documentary film in Malayalam language, directed by Sathish Kalathil.', " The film shot in digital format and it produced by Kalathil Creative Heads under the banner of Akhil Krishna Films, released in 2008, of 28.23 minutes' duration.", ' The documentary is the first experimental work which shot through a mobile phone camera in India.', ' Nokia N70 music edition mobile phone with 2 megapixel video resolution was fully used to capture the film.', ' In the period of "Veena Vaadanam", it was the only eligible and costly camera phone to capture videos with a best visual quality.', ' After post production works, the output can telecast with a comfortable visual clarity in Television or screen with a projector .']], ['Jalachhayam', ["Jalachhayam (മലയാളം: ) is a 2010 Indian Malayalam-language Experimental film, produced and directed by Sathish Kalathil under the banner of 'The People's Films'.", ' The story was written by Sujith Aalungal and describes the warm relationship between a village man and an artist (painter) from the city.']], ['Sathish Kalathil', ['Sathish Kalathil (മലയാളം: ) is an Indian film and documentary Director and Producer in malayalam.', ' He is also Story Writer, and Lyricist.', ' His experimental works are well known and appropriately discussed in Malayalam Cinema industry and his debut movie Jalachhayam (2010) was well discussed according to its experimental approach.', ' Actually, his first venture was in 2008 named Veena Vaadanam, a documentary film about Art (Painting) and that was his first experimental entry in movie.', ' In 2012, he directed Laloorinu Parayanullathu, a social committed documentary film about Municipal solid waste.']], ['Bangladesh Film Directors Association', ['Bangladesh Film Directors Association is the pan-national trade body of film directors in Bangladesh.', ' The Bangladesh Film Directors Association’s General Secretary is Badiul Alam Khokon.', ' Mushfiqur Rahman Gulzar is the president of Bangladesh Film Directors Association.']], ['Influence of Stanley Kubrick', ['Stanley Kubrick is regarded by film critics and historians as one of the most influential directors of all time.', ' Leading directors, including Martin Scorsese, Steven Spielberg, George Lucas, James Cameron, Woody Allen, Terry Gilliam, the Coen Brothers, Ridley Scott, Paul Thomas Anderson, Christopher Nolan, David Lynch, and George A. Romero, have cited Kubrick as a source of inspiration, and in the case of Spielberg, collaboration.', ' In an interview for the "Eyes Wide Shut" DVD release, Steven Spielberg comments that "nobody could shoot a picture better in history", and that Kubrick told stories in a way "antithetical to the way we are accustomed to receiving stories".', ' Writing in the introduction to a recent edition of Michel Ciment\'s "Kubrick", film director Martin Scorsese notes most of Kubrick\'s films were misunderstood and under-appreciated when first released, only to be considered masterpieces later on.']], ['Laloorinu Parayanullathu', ['Laloorinu Parayanullathu (What Has Laloor To Say) (മലയാളം: ) is an Indian documentary film directed by Sathish Kalathil in Malayalam Language.', ' The documentary narrates about the problems of Municipal Garbage dumping in Laloor, a suburban area in Thrissur Municipal Corporation.', ' The film reveals the history of the waste dumping in Laloor since the period of Sakthan Thampuran who was the ruler of the Kingdom of Cochin and first violence against the Garbage dumping here.']], ['Zeitgeist Films', ['Zeitgeist Films is an American independent film distributor based in New York City founded in 1988 by co-Presidents Nancy Gerstman and Emily Russo.', ' Films distributed by Zeitgeist are strongly auteur-driven by directors such as Christopher Nolan, Guy Maddin, Atom Egoyan, Todd Haynes, Nuri Bilge Ceylan, Olivier Assayas, Abbas Kiarostami, Deepa Mehta, Jan Švankmajer and the Brothers Quay.', ' The expansive Zeitgeist film library includes "Trouble the Water", "The Corporation", "Jellyfish", "Examined Life", "Into Great Silence", Ten and Irma Vep.', ' In June 2008, the MoMA honored two decades of Zeitgeist successes with a month-long, twenty film retrospective entitled "Zeitgeist: The Films of Our Time", exhibiting the distributor\'s twenty most critically acclaimed, intellectually stimulating titles.']]], 'answer': 'yes', '_id': '5ae40c465542996836b02c25', 'type': 'comparison'})
parallelQaAndEvaluate completing: 100%|██████████| 2/2 [00:00<00:00, 125.54it/s]
Traceback (most recent call last):
  File "/teamspace/studios/this_studio/KAG/kag/examples/hotpotqa/./solver/evaForHotpotqa.py", line 124, in <module>
    total_metrics = evaObj.parallelQaAndEvaluate(
  File "/teamspace/studios/this_studio/KAG/kag/examples/hotpotqa/./solver/evaForHotpotqa.py", line 104, in parallelQaAndEvaluate
    res_metrics[item_key] = item_value / total_metrics["processNum"]
ZeroDivisionError: float division by zero

**Comment by PimelY567** [comment]
knext project restore --host_addr http://127.0.0.1:8887 --proj_path .
knext schema commit
python ./builder/indexer.py
python ./solver/evaForHotpotqa.py <----Error Here

**Comment by Sternstunde34** [comment]
+1 the same error

**Comment by northmachine** [comment]
Hello, the issue has been resolved in the pull request at https://github.com/OpenSPG/KAG/pull/29. Please give it another try.
