### ISSUE TITLE
怎么删除知识库

### ISSUE THREAD

**Issue by moming975** [OpenSPG/KAG#31]
做测试只能新建知识库，重新测试只能重建知识库。旧知识库怎么删除

![image](https://github.com/user-attachments/assets/4e7c0dc0-d0d5-45be-8e8a-78e627b3dac9)
没找到对应功能，knext语句也没找到对应功能

**Comment by andylau-55** [comment]
Thank you for your feedback. We will support the deletion of the knowledge base in the next version

**Comment by xionghuaidong** [comment]
Since dozerdb (a community version of Neo4j) does not deleting graph databases. We can not implement the knowledge base deletion feature for the moment.

**Comment by caszkgui** [comment]
> 做测试只能新建知识库，重新测试只能重建知识库。旧知识库怎么删除
> 
> ![image](https://private-user-images.githubusercontent.com/103560656/383801257-4e7c0dc0-d0d5-45be-8e8a-78e627b3dac9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxOTMzMTcsIm5iZiI6MTczMjE5MzAxNywicGF0aCI6Ii8xMDM1NjA2NTYvMzgzODAxMjU3LTRlN2MwZGMwLWQwZDUtNDViZS04ZThhLTc4ZTYyN2IzZGFjOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyMVQxMjQzMzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NmVjNTA2YmYxMzcxNzQ2N2JlMDgxZGY2N2QzYjgzYjI2ZTA4MDBjZDkzZGZmODNlMmRiMzlkMTY3M2JjMDk1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.JACAQXFi2x1-rb0_2kmTf_FMzL6tMMAu1b_Pt5mf2oQ) 没找到对应功能，knext语句也没找到对应功能

knowledge base deletion has been supported in kag v0.5.1 : https://github.com/OpenSPG/KAG/releases/tag/v0.5.1
