### ISSUE TITLE
服务端镜像安装失败

### ISSUE THREAD

**Issue by Yue-Rain** [OpenSPG/KAG#32]
执行产品使用说明中的服务端安装镜像：
`docker-compose -f docker-compose.yml up -d`
报错：

stat: cannot statx '/logs': Operation not permitted
Warning: Folder mounted to "/logs" is not writable from inside container. Changing folder owner to neo4j.
stat: cannot statx '/data': Operation not permitted
Warning: Folder mounted to "/data" is not writable from inside container. Changing folder owner to neo4j.
stat: cannot statx '/data/dbms': Operation not permitted
Warning: Folder mounted to "/data/dbms" is not writable from inside container. Changing folder owner to neo4j.
Installing Plugin 'apoc' from /var/lib/neo4j/labs/apoc-*-core.jar to /var/lib/neo4j/plugins/apoc.jar
stat: cannot statx '/var/lib/neo4j/plugins/apoc.jar': Operation not permitted
Plugin at '/var/lib/neo4j/plugins/apoc.jar' is not readable
stat: cannot statx '/logs': Operation not permitted
Warning: Folder mounted to "/logs" is not writable from inside container. Changing folder owner to neo4j.
stat: cannot statx '/data': Operation not permitted
Warning: Folder mounted to "/data" is not writable from inside container. Changing folder owner to neo4j.
stat: cannot statx '/data/dbms': Operation not permitted
Warning: Folder mounted to "/data/dbms" is not writable from inside container. Changing folder owner to neo4j.
Installing Plugin 'apoc' from /var/lib/neo4j/labs/apoc-*-core.jar to /var/lib/neo4j/plugins/apoc.jar
stat: cannot statx '/var/lib/neo4j/plugins/apoc.jar': Operation not permitted
Plugin at '/var/lib/neo4j/plugins/apoc.jar' is not readable

docker信息如下：
`
Client:
 Debug Mode: false

Server:
 Containers: 3
  Running: 2
  Paused: 0
  Stopped: 1
 Images: 3
 Server Version: 19.03.12
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: nvidia runc
 Default Runtime: nvidia
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: 3f2f8b84a77f73d38244dd690525642a72156c64-dirty
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.17.11-1.el7.elrepo.x86_64
 Operating System: CentOS Linux 7 (Core)
 OSType: linux
 Architecture: x86_64
`

**Comment by andylau-55** [comment]
From the logs you provided, it appears that you are experiencing permission issues when using a Neo4j Docker container. The container is unable to access or write to the mounted directories. This is typically due to improper permission settings on the host directories or insufficient permissions for the container user to access the mounted directories. 
Initialization scripts or startup scripts may try to change ownership or permissions of files and directories. Ensure these scripts are run with sufficient privileges.
Ensure that the directories being mounted into the container have the correct read and write permissions on the host machine. You can use chmod and chown commands to modify the directory permissions.
Assuming your mount points are:
/logs
/data
/data/dbms
You can modify their permissions as follows:

sudo chmod -R 775 /logs /data /data/dbms
sudo chown -R $(id -u):$(id -g) /logs /data /data/dbms

**Comment by Yue-Rain** [comment]
> stat: cannot statx '/logs': Operation not permitted
Warning: Folder mounted to "/logs" is not writable from inside container. Changing folder owner to neo4j.
stat: cannot statx '/data': Operation not permitted
Warning: Folder mounted to "/data" is not writable from inside container. Changing folder owner to neo4j.
stat: cannot statx '/data/dbms': Operation not permitted
Warning: Folder mounted to "/data/dbms" is not writable from inside container. Changing folder owner to neo4j.
Installing Plugin 'apoc' from /var/lib/neo4j/labs/apoc-*-core.jar to /var/lib/neo4j/plugins/apoc.jar
stat: cannot statx '/var/lib/neo4j/plugins/apoc.jar': Operation not permitted
Plugin at '/var/lib/neo4j/plugins/apoc.jar' is not readable
stat: cannot statx '/logs': Operation not permitted
Warning: Folder mounted to "/logs" is not writable from inside container. Changing folder owner to neo4j.
stat: cannot statx '/data': Operation not permitted
Warning: Folder mounted to "/data" is not writable from inside container. Changing folder owner to neo4j.
stat: cannot statx '/data/dbms': Operation not permitted
Warning: Folder mounted to "/data/dbms" is not writable from inside container. Changing folder owner to neo4j.
Installing Plugin 'apoc' from /var/lib/neo4j/labs/apoc-*-core.jar to /var/lib/neo4j/plugins/apoc.jar
stat: cannot statx '/var/lib/neo4j/plugins/apoc.jar': Operation not permitted
Plugin at '/var/lib/neo4j/plugins/apoc.jar' is not readable
stat: cannot statx '/logs': Operation not permitted
Warning: Folder mounted to "/logs" is not writable from inside container. Changing folder owner to neo4j.
stat: cannot statx '/data': Operation not permitted
Warning: Folder mounted to "/data" is not writable from inside container. Changing folder owner to neo4j.
Installing Plugin 'apoc' from /var/lib/neo4j/labs/apoc-*-core.jar to /var/lib/neo4j/plugins/apoc.jar
stat: cannot statx '/var/lib/neo4j/plugins/apoc.jar': Operation not permitted
Plugin at '/var/lib/neo4j/plugins/apoc.jar' is not readable

已将挂载权限进行了修改，如下：

> drwxrwxr-x 2 7474 7474 4096 11月  8 09:56 data
drwxrwxr-x 2 7474 7474 4096 11月  8 09:56 logs

docker映射如下：
- /data/erhang/KAG/neo4j/logs:/logs
- /data/erhang/KAG/neo4j/data:/data

**Comment by caszkgui** [comment]
> > stat: cannot statx '/logs': Operation not permitted
> > Warning: Folder mounted to "/logs" is not writable from inside container. Changing folder owner to neo4j.
> > stat: cannot statx '/data': Operation not permitted
> > Warning: Folder mounted to "/data" is not writable from inside container. Changing folder owner to neo4j.
> > stat: cannot statx '/data/dbms': Operation not permitted
> > Warning: Folder mounted to "/data/dbms" is not writable from inside container. Changing folder owner to neo4j.
> > Installing Plugin 'apoc' from /var/lib/neo4j/labs/apoc-_-core.jar to /var/lib/neo4j/plugins/apoc.jar
> > stat: cannot statx '/var/lib/neo4j/plugins/apoc.jar': Operation not permitted
> > Plugin at '/var/lib/neo4j/plugins/apoc.jar' is not readable
> > stat: cannot statx '/logs': Operation not permitted
> > Warning: Folder mounted to "/logs" is not writable from inside container. Changing folder owner to neo4j.
> > stat: cannot statx '/data': Operation not permitted
> > Warning: Folder mounted to "/data" is not writable from inside container. Changing folder owner to neo4j.
> > stat: cannot statx '/data/dbms': Operation not permitted
> > Warning: Folder mounted to "/data/dbms" is not writable from inside container. Changing folder owner to neo4j.
> > Installing Plugin 'apoc' from /var/lib/neo4j/labs/apoc-_-core.jar to /var/lib/neo4j/plugins/apoc.jar
> > stat: cannot statx '/var/lib/neo4j/plugins/apoc.jar': Operation not permitted
> > Plugin at '/var/lib/neo4j/plugins/apoc.jar' is not readable
> > stat: cannot statx '/logs': Operation not permitted
> > Warning: Folder mounted to "/logs" is not writable from inside container. Changing folder owner to neo4j.
> > stat: cannot statx '/data': Operation not permitted
> > Warning: Folder mounted to "/data" is not writable from inside container. Changing folder owner to neo4j.
> > Installing Plugin 'apoc' from /var/lib/neo4j/labs/apoc-*-core.jar to /var/lib/neo4j/plugins/apoc.jar
> > stat: cannot statx '/var/lib/neo4j/plugins/apoc.jar': Operation not permitted
> > Plugin at '/var/lib/neo4j/plugins/apoc.jar' is not readable
> 
> 已将挂载权限进行了修改，如下：
> 
> > drwxrwxr-x 2 7474 7474 4096 11月  8 09:56 data
> > drwxrwxr-x 2 7474 7474 4096 11月  8 09:56 logs
> 
> docker映射如下：
> 
> * /data/erhang/KAG/neo4j/logs:/logs
> * /data/erhang/KAG/neo4j/data:/data

Have your problem been solved ？
