### ISSUE TITLE
Graph not sync to openspg-server after building index

### ISSUE THREAD

**Issue by zxsimple** [OpenSPG/KAG#33]
**Project Configuration**
```
{"database":"medicine","password":"neo4j@openspg","uri":"neo4j://release-openspg-neo4j:7687","user":"neo4j"}
```

After execution of `python ./builder/indexer.py`, it shows KGWriter finished, but knowledge base and graph not shown on web.

```
Processing KAGExtractor: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [02:01<00:00, 60.97s/it]
Processing BatchVectorizer: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:32<00:00, 16.33s/it]
Processing KGWriter: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:05<00:00,  2.73s/it]
Processing CSVReader: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 400.37it/s]
Processing SPOMapping: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████| 14/14 [00:00<00:00, 68839.69it/s]
Processing BatchVectorizer: 100%|███████████████████████████████████████████████████████████████████████████████████████████████| 14/14 [00:00<00:00, 18.91it/s]
Processing KGWriter: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████| 14/14 [00:00<00:00, 28.08it/s]
```

<img width="1324" alt="image" src="https://github.com/user-attachments/assets/c5e640ca-d236-4170-b251-9f07cfaf08d1">

**Comment by xionghuaidong** [comment]
The graph you see is the concept graph, not the entity graph.
To see the imported data, you can view it in the Neo4j browser. Please navigate to <http://127.0.0.1:7474>.

**Comment by zxsimple** [comment]
Thanks!

**Comment by Wangzhongxi** [comment]
> 您看到的图形是概念图，而不是实体图。要查看导入的数据，您可以在 Neo4j 浏览器中查看它。请导航到 http://127.0.0.1:7474。
![image](https://github.com/user-attachments/assets/f57719f3-6e3b-44ac-83d4-3d075487f12c)

![image](https://github.com/user-attachments/assets/cd2c8c27-e8cd-44b6-b2ff-e409689a4e24)

wo'zhe'li我这里也是构建完成，为什么在neo4j中查看不到图谱结构

**Comment by Wangzhongxi** [comment]
> 谢谢！
 你好，你这个可以在neo4j中查看到图谱结构吗，运行index.py重构图谱文件后还要其他操作吗？求解答

**Comment by caszkgui** [comment]
> > 您看到的图形是概念图，而不是实体图。要查看导入的数据，您可以在 Neo4j 浏览器中查看它。请导航到 [http://127.0.0.1:7474。](http://127.0.0.1:7474%E3%80%82)
> > ![image](https://private-user-images.githubusercontent.com/135239375/384392510-f57719f3-6e3b-44ac-83d4-3d075487f12c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzExNDIxMjgsIm5iZiI6MTczMTE0MTgyOCwicGF0aCI6Ii8xMzUyMzkzNzUvMzg0MzkyNTEwLWY1NzcxOWYzLTZlM2ItNDRhYy04M2Q0LTNkMDc1NDg3ZjEyYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwOVQwODQzNDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZjE3MzA3OGRhNTExYjdlZTM5Y2JmNTU1YTZkYTJmN2UwMDFjOTY5MDBiOWU2NDFiMmViYzUxZTc1NGE5MGFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.7ewvMG7cIcJtJgXDjJH6gt2AobGpHClW-NNti7AnwQ0)
> 
> ![image](https://private-user-images.githubusercontent.com/135239375/384392362-cd2c8c27-e8cd-44b6-b2ff-e409689a4e24.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzExNDIxMjgsIm5iZiI6MTczMTE0MTgyOCwicGF0aCI6Ii8xMzUyMzkzNzUvMzg0MzkyMzYyLWNkMmM4YzI3LWU4Y2QtNDRiNi1iMmZmLWU0MDk2ODlhNGUyNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwOVQwODQzNDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNDQ4YjMwYWQ3M2E2MTI3MDllZDNiZmE5ZjYzYjc5MWY3ZGEwYzUwMWI4MTgzM2VhNTg0MDk2MzMzMmUyYjg5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.EsrtJXGlb2XtO8N5RATKBY-tP7zOenwIpUDJIjFQFaQ)
> 
> wo'zhe'li我这里也是构建完成，为什么在neo4j中查看不到图谱结构

 you can change the database through neo4j webui:
![image](https://github.com/user-attachments/assets/8e7fc242-bbf1-4341-afcc-68721c5c419f)

**Comment by Wangzhongxi** [comment]
> > > 您看到的图形是概念图，而不是实体图。要查看导入的数据，您可以在 Neo4j 浏览器中查看它。请导航到 [http://127.0.0.1:7474。](http://127.0.0.1:7474%E3%80%82)
> > > ![图像](https://private-user-images.githubusercontent.com/135239375/384392510-f57719f3-6e3b-44ac-83d4-3d075487f12c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzExNDIxMjgsIm5iZiI6MTczMTE0MTgyOCwicGF0aCI6Ii8xMzUyMzkzNzUvMzg0MzkyNTEwLWY1NzcxOWYzLTZlM2ItNDRhYy04M2Q0LTNkMDc1NDg3ZjEyYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwOVQwODQzNDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZjE3MzA3OGRhNTExYjdlZTM5Y2JmNTU1YTZkYTJmN2UwMDFjOTY5MDBiOWU2NDFiMmViYzUxZTc1NGE5MGFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.7ewvMG7cIcJtJgXDjJH6gt2AobGpHClW-NNti7AnwQ0)
> > 
> > 
> > ![图像](https://private-user-images.githubusercontent.com/135239375/384392362-cd2c8c27-e8cd-44b6-b2ff-e409689a4e24.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzExNDIxMjgsIm5iZiI6MTczMTE0MTgyOCwicGF0aCI6Ii8xMzUyMzkzNzUvMzg0MzkyMzYyLWNkMmM4YzI3LWU4Y2QtNDRiNi1iMmZmLWU0MDk2ODlhNGUyNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwOVQwODQzNDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNDQ4YjMwYWQ3M2E2MTI3MDllZDNiZmE5ZjYzYjc5MWY3ZGEwYzUwMWI4MTgzM2VhNTg0MDk2MzMzMmUyYjg5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.EsrtJXGlb2XtO8N5RATKBY-tP7zOenwIpUDJIjFQFaQ)
> > wo'zhe'li我这里也是构建完成，为什么在neo4j中查看不到图谱结构
> 
> 您可以通过 Neo4j WebUI 更改数据库： ![图像](https://private-user-images.githubusercontent.com/15404227/384590535-8e7fc242-bbf1-4341-afcc-68721c5c419f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzExNDcxMDQsIm5iZiI6MTczMTE0NjgwNCwicGF0aCI6Ii8xNTQwNDIyNy8zODQ1OTA1MzUtOGU3ZmMyNDItYmJmMS00MzQxLWFmY2MtNjg3MjFjNWM0MTlmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA5VDEwMDY0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzMTEyMmFjYmEyNjM3NzJhOTZhYmJkYjY0Yjk3ZDM2NmFlNjVhMjU1MmViM2E2NTllMWViNTgwMTkyYjZjYWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.cEUPMOASL3rZjqVFGvebyUwugwZq8PTHD9OQoxCPgho)

好的，谢谢了
