### ISSUE TITLE
invalid vectorizer config: model not found

### ISSUE THREAD

**Issue by xsg5886779** [OpenSPG/KAG#34]
<class 'RuntimeError'>: invalid vectorizer config: model not found at '/var/www/models/bge-m3', nor model url specified

配置文件：
namespace = KagDemo
host_addr = http://localhost:8887
id = 1

[vectorizer]
vectorizer = kag.common.vectorizer.LocalBGEVectorizer
model = /var/www/models/bge-m3
vector_dimensions = 768

[llm]
client_type = vllm
base_url = http://192.168.100.86:8000/v1/chat/completions
api_key = put your deepseek api key her
model = qwen25-7B-chat

[prompt]
biz_scene = default
language = zh

model = /var/www/models/bge-m3  这个是存在的
model = qwen25-7B-chat  也是存在的，但是就是创建不了知识库

**Comment by xionghuaidong** [comment]
> model not found at '/var/www/models/bge-m3'

'/var/www/models/bge-m3' is not a directory in the **release-openspg-server** container.

Only '~/.cache/vectorizer/BAAI/bge-base-zh-v1.5' exists in the **release-openspg-server** container.

By the way, the key ``model`` is incorrect, it should be ``path``. And the ``bge-m3`` model has ``vector_dimensions = 1024``.

If you want to use the ``bge-m3`` model like the built-in ``bge-base-zh-v1.5`` model. You should copy the ``bge-m3`` models files into the **release-openspg-server** container to a location like ``~/.cache/vectorizer/BAAI/bge-m3``, then use the following config.

```text
[vectorizer]
vectorizer = kag.common.vectorizer.LocalBGEM3Vectorizer
path = ~/.cache/vectorizer/BAAI/bge-m3
vector_dimensions = 1024
```
