### ISSUE TITLE
ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by zxy66688** [OpenSPG/KAG#35]
When run "python ./solver/evaForMusique.py"
still the problem:

Traceback (most recent call last):
  File "F:\openspg\KAG\kag\examples\musique\solver\evaForMusique.py", line 135, in <module>
    total_metrics = evaObj.parallelQaAndEvaluate(
  File "F:\openspg\KAG\kag\examples\musique\solver\evaForMusique.py", line 115, in parallelQaAndEvaluate
    res_metrics[item_key] = item_value / total_metrics["processNum"]
ZeroDivisionError: float division by zero

how to solve it?

**Comment by xionghuaidong** [comment]
Hello, the issue has been resolved in the pull request at https://github.com/OpenSPG/KAG/pull/29. Please give it another try.

You can update your container images as follows. [Server Image Installation](https://openspg.yuque.com/ndx6g9/wc9oyq/ghxu13himevhlx64)

![image](https://github.com/user-attachments/assets/d4e58c42-9eb7-4723-9e11-df5030a12a0c)
