### ISSUE TITLE
查看抽取结果报错：unknown error system unknown error with NullPointerException

### ISSUE THREAD

**Issue by Wangzhongxi** [OpenSPG/KAG#40]
![image](https://github.com/user-attachments/assets/fd87668d-5ac6-4675-ab86-b3abc6dc0048)

**Comment by andylau-55** [comment]
Have you pulled the latest image? The latest version has solved this problem. Can you run `docker logs -f release-openspg-server` to view the stack information?

**Comment by andylau-55** [comment]
This feature has been released in version 0.5.1
https://github.com/OpenSPG/openspg/releases/tag/v0.5.1
