### ISSUE TITLE
vllm的api-key不识别

### ISSUE THREAD

**Issue by wukai123123123** [OpenSPG/KAG#47]
<img width="799" alt="截屏2024-11-15 上午11 35 30" src="https://github.com/user-attachments/assets/a808cc39-1e37-4cd4-a5a3-7679af122252">
配置vllm的api-key后保存提示错误
`{
  "client_type": "vllm",
  "base_url": "http://10.254.10.90:16000/v1/chat/completions",
  "api_key": "814e334f-117b-4e64-ac85-f97dec37c917",
  "model": "cloudtop-gest-1.5b-instruct"
}`
查看源码此处并没有设置api-key：
<img width="870" alt="截屏2024-11-15 上午11 34 38" src="https://github.com/user-attachments/assets/286584e5-25ca-45ca-94d5-2481cec3f193">

**Comment by wukai123123123** [comment]
是不是应该设置`Authorization : Bearer api-key`请求头

**Comment by caszkgui** [comment]
> 是不是应该设置`Authorization : Bearer api-key`请求头

Is your llm base_url accessible in your openspg container ?
you can test the accessibility with the help of reference: [llm service test](https://openspg.yuque.com/ndx6g9/0.5/cfiaugez2n72g08k#ybHxt)

![image](https://github.com/user-attachments/assets/aba90dc5-c5f5-4941-8d4b-5553d0790d2b)

**Comment by xionghuaidong** [comment]
Try replace
```text
"base_url": "http://10.254.10.90:16000/v1/chat/completions"
```
with
```text
"base_url": "http://10.254.10.90:16000/v1"
```
``chat/completions`` should not be part of ``base_url``.
