### ISSUE TITLE
urllib3.connectionpool: Retrying after connection broken by 'NewConnectionError' during kgwriter execution

### ISSUE THREAD

**Issue by dengxingwang1** [OpenSPG/KAG#58]
I'm encountering frequent connection issues while running the kgwriter module. The error logs show repeated retries by urllib3, ultimately failing to establish a connection. Below is the detailed error message:

WARNING:urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x69b1208b0>: Failed to establish a new connection: [Errno 61] Connection refused')': /public/v1/graph/writerGraph

If anyone has encountered a similar issue or knows of a reliable solution, I would greatly appreciate any advice.

**Comment by andylau-55** [comment]
Please check whether the openspg-server service is started normally and whether http://127.0.0.1:8887/ is accessible

**Comment by dengxingwang1** [comment]
> Please check whether the openspg-server service is started normally and whether http://127.0.0.1:8887/ is accessible

When handling slightly larger datasets, the buildKG process takes a considerable amount of time. During this extended operation, the Docker container is prone to interruptions or crashes. Upon restarting the container, connection errors like the one mentioned above are frequently encountered.

**Comment by Kid-Nob1** [comment]
在远程服务器的账号上进行该操作，是不行的吧，因为服务器账号本身就是以docker，还有其他处理办法吗

**Comment by Kid-Nob1** [comment]
> > 怎么样才能启用openspg-server service，用knext命令吗。
> 
> 参考readme中的教程： curl -sSL https://raw.githubusercontent.com/OpenSPG/openspg/refs/heads/master/dev/release/docker-compose.yml -o docker-compose.yml docker compose -f docker-compose.yml up -d 两行命令搞定

在远程服务器的账号上进行该操作，是不行的吧，因为服务器账号本身就是以docker，还有其他处理办法吗

**Comment by caszkgui** [comment]
> > Please check whether the openspg-server service is started normally and whether http://127.0.0.1:8887/ is accessible
> 
> When handling slightly larger datasets, the buildKG process takes a considerable amount of time. During this extended operation, the Docker container is prone to interruptions or crashes. Upon restarting the container, connection errors like the one mentioned above are frequently encountered.

The container crash seems to be a bug in the neo4j call, you can download the latest container version and retry: https://github.com/OpenSPG/KAG/releases/tag/v0.5.1

**Comment by thundax-lyp** [comment]
when calling KGWrtier to write data, openspg-server actually forwards the data to openspg-neo4j, which means that most of the pressure is borne by neo4j. Therefore, in addition to checking openspg server, it is also necessary to check whether neo4j is available.

**Comment by Eshan276** [comment]
> when calling KGWrtier to write data, openspg-server actually forwards the data to openspg-neo4j, which means that most of the pressure is borne by neo4j. Therefore, in addition to checking openspg server, it is also necessary to check whether neo4j is available.

i am following this developer mode guide - https://openspg.yuque.com/ndx6g9/wc9oyq/yexegklu44bqqicm#cikso  

 when exactly i have to startup the neo4j......
 i am getting the exact error while running ,knext project create --config_path ./example.cfg
