### ISSUE TITLE
知识库管理任务创建完成后问答报错? 

### ISSUE THREAD

**Issue by zhangqaws** [OpenSPG/KAG#60]
![1732089849258](https://github.com/user-attachments/assets/de6fbaff-dbab-481e-ae28-b4582db36980)

**Comment by zhangqaws** [comment]
![image](https://github.com/user-attachments/assets/f7f39528-af81-4d16-a5fe-9cff74b27ba9)    配上

**Comment by shnulailai** [comment]
你好，请问后面是怎么解决的呢？我也遇到了这个问题
