### ISSUE TITLE
csv数据加载，仿照示例riskmining读取关系自定义chain报错

### ISSUE THREAD

**Issue by Wangzhongxi** [OpenSPG/KAG#61]
class Control_Action_Chain(BuilderChainABC):
    def __init__(self, spg_type_name: str):
        super().__init__()
        self.spg_type_name = spg_type_name

    def build(self, **kwargs):
        source = CSVReader(output_type="Dict")
        subject_name, relation, object_name = self.spg_type_name.split("_")
        mapping = (
            RelationMapping(subject_name, relation, object_name)
            .add_src_id_mapping("condition")
            .add_dst_id_mapping("effect")
        )
        sink = KGWriter()
        return source >> mapping >> sink

csv数据如下：
condition,effect
高于xx水位线,关闭xx设备。

报错信息：
INFO:numexpr.utils:Note: NumExpr detected 24 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 16.
INFO:numexpr.utils:NumExpr defaulting to 16 threads.
Traceback (most recent call last):
  File "E:\LLM\code\KAG2\KAG\kag\examples\Logictugraph\builder\indexer.py", line 142, in <module>
    ControlLogicChain(spg_type_name="control_actions").invoke(file_path=os.path.join(file_path, "data/output_control_actions.csv"))
  File "C:\ProgramData\Anaconda3\envs\wllm\lib\site-packages\knext\builder\builder_chain_abc.py", line 25, in invoke
    chain = self.build(file_path=file_path, max_workers=max_workers, **kwargs)
  File "E:\LLM\code\KAG2\KAG\kag\examples\Logictugraph\builder\indexer.py", line 109, in build
    raise ValueError(f"Invalid spg_type_name format: {self.spg_type_name}. Expected format: 'subject_relation_object'")
ValueError: Invalid spg_type_name format: control_actions. Expected format: 'subject_relation_object'
但是我看示例riskmining示例中的RiskMiningRelationChain加载的数据也只包含src和dst两列数据，那为什么这里可以加载，我自定义的数据无法加载
并且怎么才算是合理的SPG type name呢，是需要在哪里重新定义还是？
![image](https://github.com/user-attachments/assets/260bfe51-df38-4fc4-89bf-12ee1b80cc20)

**Comment by thundax-lyp** [comment]
source >> mapping >> vectorizer >> sink 为啥没有 vectorizer 呢？

**Comment by thundax-lyp** [comment]
```https://github.com/OpenSPG/KAG/blob/master/kag/builder/component/mapping/relation_mapping.py``` 中

```python
        schema = SchemaClient(project_id=self.project_id).load()
        assert subject_name in schema, f"{subject_name} is not a valid SPG type name"
        assert object_name in schema, f"{object_name} is not a valid SPG type name"
```

代码上看，schma是从project的配置中加载的，去看下 knext生成的 XXXX.schema文件有没有加载到project里，如果没有，重新使用

```shell
knext schema commit
```
