### ISSUE TITLE
自带的案例里面python ./builder/indexer.py一直报错

### ISSUE THREAD

**Issue by xiaoguanbai188** [OpenSPG/KAG#69]
跑完开始
INFO:openai._base_client:Retrying request to /embeddings in 0.461742 seconds
INFO:openai._base_client:Retrying request to /embeddings in 0.464129 seconds
INFO:openai._base_client:Retrying request to /embeddings in 0.473919 seconds
开始这样，没多久就报错，最后结尾是 
 raise APIConnectionError(request=request) from err
openai.APIConnectionError: Connection error.
按文档在riskmining里面配置就改了kag_config.cfg里面的llm的api_key，其他没有动

<img width="641" alt="image" src="https://github.com/user-attachments/assets/9699160a-e135-48c2-9d75-c32c503e3e54">
到底哪里有问题

**Comment by thundax-lyp** [comment]
embedding接口没连上，POST点数据给embedding接口，测测通不通吧

**Comment by caszkgui** [comment]
> 跑完开始 INFO:openai._base_client:Retrying request to /embeddings in 0.461742 seconds INFO:openai._base_client:Retrying request to /embeddings in 0.464129 seconds INFO:openai._base_client:Retrying request to /embeddings in 0.473919 seconds 开始这样，没多久就报错，最后结尾是 raise APIConnectionError(request=request) from err openai.APIConnectionError: Connection error. 按文档在riskmining里面配置就改了kag_config.cfg里面的llm的api_key，其他没有动
> 
> <img alt="image" width="641" src="https://private-user-images.githubusercontent.com/189608157/389481972-9699160a-e135-48c2-9d75-c32c503e3e54.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyNzcxNTMsIm5iZiI6MTczMzI3Njg1MywicGF0aCI6Ii8xODk2MDgxNTcvMzg5NDgxOTcyLTk2OTkxNjBhLWUxMzUtNDhjMi05ZDc1LWMzMmM1MDNlM2U1NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNFQwMTQ3MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYTkyZGU3NWI3NTI2MjdjYTBmOWY0ODNhOGM0YjU0NjNkNTI0MTQyYmE3MDY0NGQzMzBlMzA4ZmI5OWRmZWUyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.v4jDRk4uhsW2nQcF7E9fzpvU8VPHNvXGNTkgxcxmE8g"> 到底哪里有问题

You can refer to [user manual of embedding model configuration](https://openspg.yuque.com/ndx6g9/0.5/yofw66sq5ncerf4i#Yl3AZ) and check whether your embedding model service is accessible.

![image](https://github.com/user-attachments/assets/f94a6945-5ef0-4f4f-ac48-6176b4a0d16b)
