### ISSUE TITLE
default_reflextor.py代码中的self.llm_module.invoke的judge模块永遠無法執行，怀疑有bug

### ISSUE THREAD

**Issue by zhangyanbo2007** [OpenSPG/KAG#70]
def _can_answer(self, memory: KagMemoryABC, instruction: str):
        """
        Determines whether the query can be answered.

        :param memory (KagMemory): The context or memory information to use for rewriting.
        :param instruction (str): The original instruction to be rewritten.
        :return: Whether the query can be answered (boolean)
        """
        serialize_memory = self._get_serialize_memory(memory)
        if serialize_memory == "":
            return False

        if memory.get_solved_answer() != "":
            return True

        return self.llm_module.invoke({'memory': serialize_memory, 'instruction': instruction}, self.judge_prompt,
                                      with_json_parse=False)
                                      
         直接用hotpotqa數據集測試。
         測例：Are Christopher Nolan and Sathish Kalathil both film directors?

**Comment by royzhao** [comment]
hi，[https://github.com/OpenSPG/KAG/pull/97](url) 在这个分支上修复了这个bug，后续会发布一个reproduce脚本辅助大家复现指标
