### ISSUE TITLE
404 error: public/v1/project/update

### ISSUE THREAD

**Issue by tpoisonooo** [OpenSPG/KAG#78]
感觉是 openspg server 版本和 KAG client 版本没对上。
报错：

```bash
HTTP response headers: HTTPHeaderDict({'Vary': 'Origin, Access-Control-Request-Method, Access-Control-Request-Headers', 'Content-Type': 'application/json;charset=UTF-8', 'Transfer-Encoding': 'chunked', 'Date': 'Wed, 27 Nov 2024 10:49:51 GMT'})
HTTP response body: {"timestamp":"2024-11-27 18:49:51","status":404,"error":"Not Found","path":"/public/v1/project/update"}
```

server 用的 docker-compose
```bash
openspg md5sum docker-compose.yml 
789790f5ff0110d51a8c13826c74d003  docker-compose.yml
```

client 用的main， 1126 的版本  commit  16594ed09d0a49f63f8f57da991c74b61295cec4

**Comment by caszkgui** [comment]
> 感觉是 openspg server 版本和 KAG client 版本没对上。 报错：
> 
> ```shell
> HTTP response headers: HTTPHeaderDict({'Vary': 'Origin, Access-Control-Request-Method, Access-Control-Request-Headers', 'Content-Type': 'application/json;charset=UTF-8', 'Transfer-Encoding': 'chunked', 'Date': 'Wed, 27 Nov 2024 10:49:51 GMT'})
> HTTP response body: {"timestamp":"2024-11-27 18:49:51","status":404,"error":"Not Found","path":"/public/v1/project/update"}
> ```
> 
> server 用的 docker-compose
> 
> ```shell
> openspg md5sum docker-compose.yml 
> 789790f5ff0110d51a8c13826c74d003  docker-compose.yml
> ```
> 
> client 用的main， 1126 的版本 commit [16594ed](https://github.com/OpenSPG/KAG/commit/16594ed09d0a49f63f8f57da991c74b61295cec4)

It looks like your openspg server docker image is not the latest，you need to  delete your local docker images and the pull again.

**Comment by tpoisonooo** [comment]
I have removed docker images and re-install, here is the new error:

![image](https://github.com/user-attachments/assets/a851fa38-ac0a-4903-bf47-487df1181b78)

**Comment by caszkgui** [comment]
> I have removed docker images and re-install, here is the new error:
> 
> ![image](https://private-user-images.githubusercontent.com/7872421/390406510-a851fa38-ac0a-4903-bf47-487df1181b78.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3MTY2MzgsIm5iZiI6MTczMjcxNjMzOCwicGF0aCI6Ii83ODcyNDIxLzM5MDQwNjUxMC1hODUxZmEzOC1hYzBhLTQ5MDMtYmY0Ny00ODdkZjExODFiNzgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMjdUMTQwNTM4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmMzNjQ3Njg3ODRjZGJlMzM2ODY4ZGFlNjg1ZTI0NDQ0OWNhYjYwZWVlZDQ3ZjAxZTc1YjAzYmMyZDUxOWZhNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.nkNXoiUE9Y35NHJPEr9hlTC4TJS5EjaMfBsxTH2GFh0)

Is `/root/.cache/vectorizer/BAAI/bge-base-zh-v1.5` your local dir, or dir inside the container？
could you give a complete description of your enviroment? such as operating system，your docker version， etc.

**Comment by tpoisonooo** [comment]
Here is my env:

* os : Ubuntu 20.04.5 LTS
* docker:   version 20.10.18, build b40c2f6

Since  docker is register the layer,  I guess  `/root/.cache/vectorizer/BAAI/bge-base-zh-v1.5`  comes from the **container**.

**Comment by tpoisonooo** [comment]
I have rerun the comand with `sudo `,  the problem solved.

```bash
sudo docker compose -f docker-compose.yml up -d
```

**Comment by tpoisonooo** [comment]
![image](https://github.com/user-attachments/assets/723707a4-2ed7-4950-980f-935298e03cc6)

Another little question: `knext project create` would eat my `kag_config.cfg`. 

![image](https://github.com/user-attachments/assets/b693aa3c-37d2-49ae-9988-07ad3191beb6)
