### ISSUE TITLE
为什么示例里面的schema都只有实体的定义？为什么没有关系定义？

### ISSUE THREAD

**Issue by zhangyanbo2007** [OpenSPG/KAG#8]
为什么示例里面的schema（2wiki, hotpotqa, KagDemo,musique）都只有实体的定义？为什么没有关系定义？这个schema定义的太简单了吧

**Comment by caszkgui** [comment]
1、directory of (examples/medicine, examples/supplychain, examples/riskmining) has schema of spg format, which consists of entityTypes， relationTypes,  and concept rules.
2、in public domain, such as 2wiki,hotpotqa,musique, kag just define entityTypes in schema, and assign relationship extraction to llm.

**Comment by caszkgui** [comment]
> 1、directory of (examples/medicine, examples/supplychain, examples/riskmining) has schema of spg format, which consists of entityTypes， relationTypes, and concept rules.
> 2、in public domain, such as 2wiki,hotpotqa,musique, kag just define entityTypes in schema, and assign relationship extraction to llm.

1、directory of (examples/medicine, examples/supplychain, examples/riskmining) has schema of spg format, which consists of entityTypes， relationTypes, and concept rules.
2、in public domain, such as 2wiki,hotpotqa,musique, kag just define entityTypes in schema, and assign relationship extraction to llm.

**Comment by leywar** [comment]
Based on the semantic representation of `SPG`, `KAG` will extract knowledge according to the definition of `Schema` by default. If the user configures the extraction of knowledge beyond the definition of Schema, KAGExtractor will enable schema-free extraction based on `Large Language Models` to automatically complete relations and properties. This method is more suitable for document information retrieval scenarios. Data sets such as hotpotqa and 2wiki are all document retrieval tasks.
