### ISSUE TITLE
开发者版执行knext schema commit的时候报错，提示无法匹配到另一个项目

### ISSUE THREAD

**Issue by yuuki-nanamin** [OpenSPG/KAG#85]
knext.common.rest.exceptions.ApiException: (500)
Reason:
HTTP response headers: HTTPHeaderDict({'Vary': 'Origin, Access-Control-Request-Method, Access-Control-Request-Headers', 'Remote': '172.21.0.4', 'Content-Type': 'application/json;charset=UTF-8', 'Transfer-Encoding': 'chunked', 'Date': 'Thu, 28 Nov 2024 12:31:12 GMT', 'Connection': 'close'})
HTTP response body: "type name: Medicine.Chunk not match project namespace: JaySinger"

其中Medicine和JaySinger是两个不同的项目

**Comment by caszkgui** [comment]
> knext.common.rest.exceptions.ApiException: (500) Reason: HTTP response headers: HTTPHeaderDict({'Vary': 'Origin, Access-Control-Request-Method, Access-Control-Request-Headers', 'Remote': '172.21.0.4', 'Content-Type': 'application/json;charset=UTF-8', 'Transfer-Encoding': 'chunked', 'Date': 'Thu, 28 Nov 2024 12:31:12 GMT', 'Connection': 'close'}) HTTP response body: "type name: Medicine.Chunk not match project namespace: JaySinger"
> 
> 其中Medicine和JaySinger是两个不同的项目

check your namespace setting of your schema file.
