### ISSUE TITLE
每次点击相同文档的“抽取结果”返回的内容都不一样？

### ISSUE THREAD

**Issue by ryzn0518** [OpenSPG/KAG#87]
能观察到的现象是每次点同一份处理好的文档，“抽取结果”都不一样。

尝试找了原因没有找到，我看每次前端请求的 api 其中 ctoken值传的不一样，请求的接口是 /schema/diff

请问，这个不一样的原因是什么？

因为我们会奇怪，是我们抽取结果是错的还是每次根据原始数据随机生成的抽取结果的图？

**Comment by andylau-55** [comment]
The results here are randomly sampled data. We will provide subgraph query capabilities in subsequent versions. If you want to view the complete data currently, you can view it through http://127.0.0.1:7474/

**Comment by yuuki-nanamin** [comment]
> The results here are randomly sampled data. We will provide subgraph query capabilities in subsequent versions. If you want to view the complete data currently, you can view it through http://127.0.0.1:7474/

![image](https://github.com/user-attachments/assets/55b80458-35a3-4285-b864-c38195644148)

**Comment by caszkgui** [comment]
> > The results here are randomly sampled data. We will provide subgraph query capabilities in subsequent versions. If you want to view the complete data currently, you can view it through http://127.0.0.1:7474/
> 
> ![image](https://private-user-images.githubusercontent.com/188564328/392200951-55b80458-35a3-4285-b864-c38195644148.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyODgyNDgsIm5iZiI6MTczMzI4Nzk0OCwicGF0aCI6Ii8xODg1NjQzMjgvMzkyMjAwOTUxLTU1YjgwNDU4LTM1YTMtNDI4NS1iODY0LWMzODE5NTY0NDE0OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNFQwNDUyMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYWVmZGNlYzA0MzIyYTZhOTUzOWIyNTIxNzNhZjNhMmNiZGE2OTk5N2M5NjEwY2U1NjM5OGI3MjYyOWFiYjg0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.UGA3Mj_gWH-a5TxgEjufb739FISNBhBOGx0vohYLkzw)

you can find user_name， password in [docker_compose.yml](https://github.com/OpenSPG/openspg/blob/master/dev/release/docker-compose.yml)
