### ISSUE TITLE
mysql镜像没有没有初始化脚本，对应的数据库与表不存在

### ISSUE THREAD

**Issue by fushengwuyu** [OpenSPG/KAG#92]

**Comment by fushengwuyu** [comment]
最新的mysql镜像：spg-registry.cn-hangzhou.cr.aliyuncs.com/spg/openspg-mysql:latest 没有设置对应的初始化脚本，导致数据库和表都为空，server启动报错：Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'openspg.kg_sys_lock' doesn't exist

**Comment by thundax-lyp** [comment]
see the attachments
[init.sql.txt](https://github.com/user-attachments/files/18005205/init.sql.txt)
